"use client";

import { useEffect, useMemo, useState, type DragEvent } from "react";
import { useRouter } from "next/navigation";

import { getOrCreateTaskMoodboard } from "@/app/actions/moodboard";
import {
  createStandardPlannerSubtasksJson,
  STD_COMPLETED_ID as STD_COMPLETED_REF,
  STD_PREPARE_ID as STD_PREPARE_REF,
  STD_TODO_ID as STD_TODO_REF,
} from "@/lib/plannerStandardSubtasks";
import type { PlannerAssignee } from "@/lib/plannerAssignees";
import { getDirectoryFromFilePath, getElectronFilePath } from "@/lib/plannerFilePath";

export const STD_PREPARE_ID = STD_PREPARE_REF;
export const STD_TODO_ID = STD_TODO_REF;
export const STD_COMPLETED_ID = STD_COMPLETED_REF;

export type PlannerSubTask = {
  id: string;
  title: string;
  isCompleted: boolean;
  isStandard: boolean;
};

export function createStandardPlannerSubtasks(taskTitle: string): PlannerSubTask[] {
  return createStandardPlannerSubtasksJson(taskTitle) as PlannerSubTask[];
}

export type PlannerTaskLabel = "Studio" | "Photoshoot" | "Social Media" | null;

export type PlannerModalTask = {
  id: string;
  title: string;
  description: string;
  subtasks: PlannerSubTask[];
  status: "master" | "planning" | "processing" | "completed";
  isPaused: boolean;
  elapsedSeconds: number;
  startedAtSec: number | null;
  totalTimeLabel: string;
  fileLocations: string[];
  dueDate: string | null;
  recurringType: "none" | "daily" | "weekly" | "monthly";
  isAutoGenerated?: boolean;
  label?: PlannerTaskLabel;
  assignedTo?: string | null;
  /** Used to label archived assignees still attached to historical tasks. */
  assignedUsers?: PlannerAssignee[];
  clientName?: string;
  totalFee?: number | null;
};

export type PlannerModalSaveInput = {
  title: string;
  description: string;
  subtasks: PlannerSubTask[];
  dueDate: string | null;
  fileLocations: string[];
  recurringType: "none" | "daily" | "weekly" | "monthly";
  label: PlannerTaskLabel;
  assignedTo: string | null;
  clientName: string;
  totalFee: number | null;
};

export type PlannerTemplateOption = {
  id: string;
  title: string;
  description: string;
  subtasks: PlannerSubTask[];
  recurringType: "none" | "daily" | "weekly" | "monthly";
};

type PlannerTaskModalProps = {
  task: PlannerModalTask | null;
  isOpen: boolean;
  mode: "create" | "edit";
  templates: PlannerTemplateOption[];
  assigneeOptions: PlannerAssignee[];
  onClose: () => void;
  onSave: (taskId: string, updates: PlannerModalSaveInput) => void;
  onCreate: (updates: PlannerModalSaveInput) => void;
  onSaveAsTemplate: (updates: PlannerModalSaveInput) => void;
  onDelete: (taskId: string) => void;
  onPauseTask: (taskId: string) => void;
  onResumeTask: (taskId: string) => void;
};

function toDateTimeLocalInput(value: string | null): string {
  if (!value) {
    return "";
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "";
  }
  const local = new Date(parsed.getTime() - parsed.getTimezoneOffset() * 60000);
  return local.toISOString().slice(0, 16);
}

export default function PlannerTaskModal({
  task,
  isOpen,
  mode,
  templates,
  assigneeOptions,
  onClose,
  onSave,
  onCreate,
  onSaveAsTemplate,
  onDelete,
  onPauseTask,
  onResumeTask,
}: PlannerTaskModalProps) {
  const router = useRouter();
  const isCreateMode = mode === "create";
  const isFieldsLocked = Boolean(!isCreateMode && task?.isAutoGenerated);
  const [title, setTitle] = useState(task?.title ?? "");
  const [description, setDescription] = useState(task?.description ?? "");
  const [subtasks, setSubtasks] = useState<PlannerSubTask[]>(
    task?.subtasks ?? (mode === "create" ? createStandardPlannerSubtasks("") : [])
  );
  const [dueDateInput, setDueDateInput] = useState(toDateTimeLocalInput(task?.dueDate ?? null));
  const [fileLocations, setFileLocations] = useState<string[]>(task?.fileLocations ?? []);
  const [recurringType, setRecurringType] = useState<"none" | "daily" | "weekly" | "monthly">(
    task?.recurringType ?? "none"
  );
  const [label, setLabel] = useState<PlannerTaskLabel>(task?.label ?? null);
  const [openingReviewBoard, setOpeningReviewBoard] = useState(false);
  const [assignedTo, setAssignedTo] = useState<string | null>(task?.assignedTo ?? null);
  const [clientName, setClientName] = useState(task?.clientName ?? "");
  const [totalFeeInput, setTotalFeeInput] = useState(
    task?.totalFee != null && Number.isFinite(task.totalFee) ? String(task.totalFee) : ""
  );
  const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [newSubtaskText, setNewSubtaskText] = useState("");
  const [isFileDropzoneActive, setIsFileDropzoneActive] = useState(false);

  // Keep archived assignees visible when editing historical tasks.
  const effectiveAssigneeOptions = useMemo(() => {
    if (!assignedTo || assigneeOptions.some((u) => u.id === assignedTo)) {
      return assigneeOptions;
    }
    const fromHistory = (task?.assignedUsers ?? []).find((u) => u.id === assignedTo);
    return [
      ...assigneeOptions,
      {
        id: assignedTo,
        name: fromHistory?.name
          ? `${fromHistory.name} (archived)`
          : `Archived user (${assignedTo.slice(0, 8)}…)`,
      },
    ];
  }, [assigneeOptions, assignedTo, task?.assignedUsers]);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    if (task) {
      setTitle(task.title ?? "");
      setDescription(task.description ?? "");
      setSubtasks(task.subtasks ?? []);
      setDueDateInput(toDateTimeLocalInput(task.dueDate ?? null));
      setFileLocations(task.fileLocations ?? []);
      setRecurringType(task.recurringType ?? "none");
      setLabel(task.label ?? null);
      setAssignedTo(task.assignedTo ?? null);
      setClientName(task.clientName ?? "");
      setTotalFeeInput(
        task.totalFee != null && Number.isFinite(task.totalFee) ? String(task.totalFee) : ""
      );
    } else if (isCreateMode) {
      setTitle("");
      setDescription("");
      setSubtasks(createStandardPlannerSubtasks(""));
      setDueDateInput("");
      setFileLocations([]);
      setRecurringType("none");
      setLabel(null);
      setAssignedTo(null);
      setClientName("");
      setTotalFeeInput("");
    }
  }, [isOpen, task, isCreateMode]);

  useEffect(() => {
    if (!isCreateMode) {
      return;
    }
    const baseTitle = title.trim() || "Untitled Task";
    setSubtasks((prev) =>
      prev.map((s) => (s.id === STD_TODO_ID ? { ...s, title: `To-Do: ${baseTitle}` } : s))
    );
  }, [title, isCreateMode]);

  if (!isOpen) {
    return null;
  }

  const handleAddSubtask = () => {
    const trimmed = newSubtaskText.trim();
    if (!trimmed) {
      return;
    }
    setSubtasks((prev) => [
      ...prev,
      {
        id: `${task?.id ?? "new-task"}-sub-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        title: trimmed,
        isCompleted: false,
        isStandard: false,
      },
    ]);
    setNewSubtaskText("");
  };

  const handleFileDropzoneDragEnter = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsFileDropzoneActive(true);
  };

  const handleFileDropzoneDragOver = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsFileDropzoneActive(true);
  };

  const handleFileDropzoneDragLeave = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsFileDropzoneActive(false);
  };

  const handleFileDropzoneDrop = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsFileDropzoneActive(false);

    const file = event.dataTransfer.files[0];
    if (!file) {
      return;
    }

    const absolutePath = getElectronFilePath(file);
    if (absolutePath) {
      const nextPath = getDirectoryFromFilePath(absolutePath).trim();
      if (!nextPath) {
        return;
      }
      setFileLocations((prev) => {
        const cleaned = prev.map((value) => value.trim()).filter(Boolean);
        return cleaned.includes(nextPath) ? cleaned : [...cleaned, nextPath];
      });
    }
  };

  const handleUpdateLocation = (index: number, value: string) => {
    setFileLocations((prev) => {
      const next = [...prev];
      next[index] = value;
      return next;
    });
  };

  const handleRemoveLocation = (index: number) => {
    setFileLocations((prev) => prev.filter((_, i) => i !== index));
  };

  const handleAddLocation = () => {
    setFileLocations((prev) => [...prev, ""]);
  };

  const normalizeLocations = (values: string[]): string[] => {
    const seen = new Set<string>();
    const result: string[] = [];
    for (const value of values) {
      const trimmed = value.trim();
      if (!trimmed || seen.has(trimmed)) {
        continue;
      }
      seen.add(trimmed);
      result.push(trimmed);
    }
    return result;
  };

  const parseTotalFee = (value: string): number | null => {
    const normalized = value.trim().replace(",", ".");
    if (!normalized) {
      return null;
    }
    const numeric = Number(normalized);
    if (!Number.isFinite(numeric)) {
      return null;
    }
    return numeric;
  };

  const handleOpenReviewBoard = async () => {
    if (!task) {
      return;
    }
    setOpeningReviewBoard(true);
    try {
      const res = await getOrCreateTaskMoodboard(task.id, title.trim() || task.title || "Untitled Task");
      if (!res.ok) {
        window.alert(res.error);
        return;
      }
      onClose();
      router.push(`/moodboard?boardId=${encodeURIComponent(res.moodboardId)}`);
    } finally {
      setOpeningReviewBoard(false);
    }
  };

  const handleSave = () => {
    const normalizedFileLocations = normalizeLocations(fileLocations);
    const payload: PlannerModalSaveInput = {
      title: title.trim() || "Untitled Task",
      description: description.trim(),
      subtasks,
      dueDate: dueDateInput ? new Date(dueDateInput).toISOString() : null,
      fileLocations: normalizedFileLocations,
      recurringType,
      label,
      assignedTo,
      clientName: clientName.trim(),
      totalFee: parseTotalFee(totalFeeInput),
    };
    if (isCreateMode) {
      onCreate(payload);
    } else if (task) {
      onSave(task.id, payload);
    }
    onClose();
  };

  const handleLoadTemplate = (templateId: string) => {
    setSelectedTemplateId(templateId);
    const template = templates.find((item) => item.id === templateId);
    if (!template) {
      return;
    }
    setTitle(template.title);
    setDescription(template.description);
    setSubtasks(
      template.subtasks.map((s) => ({
        ...s,
        isStandard: s.isStandard || [STD_PREPARE_ID, STD_TODO_ID, STD_COMPLETED_ID].includes(s.id),
      }))
    );
    setRecurringType(template.recurringType);
    setLabel(null);
  };

  const handleSaveAsTemplate = () => {
    const normalizedFileLocations = normalizeLocations(fileLocations);
    onSaveAsTemplate({
      title: title.trim() || "Untitled Template",
      description: description.trim(),
      subtasks,
      dueDate: dueDateInput ? new Date(dueDateInput).toISOString() : null,
      fileLocations: normalizedFileLocations,
      recurringType,
      label,
      assignedTo,
      clientName: clientName.trim(),
      totalFee: parseTotalFee(totalFeeInput),
    });
  };

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4" onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="planner-task-modal-title"
        onClick={(event) => event.stopPropagation()}
        className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-zinc-900 sm:p-8"
      >
        <h2 id="planner-task-modal-title" className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
          {isCreateMode ? "Create Task" : "Task Details"}
        </h2>

        {isCreateMode ? (
          <label className="mt-4 block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Load Template
            <select
              value={selectedTemplateId}
              onChange={(event) => handleLoadTemplate(event.target.value)}
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            >
              <option value="">Select a template</option>
              {templates.map((template) => (
                <option key={template.id} value={template.id}>
                  {template.title}
                </option>
              ))}
            </select>
          </label>
        ) : null}

        <label className="mt-4 block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
          Title
          <input
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            disabled={isFieldsLocked}
            className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 disabled:cursor-not-allowed disabled:opacity-60 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
          />
        </label>

        <label className="mt-4 block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
          Description
          <textarea
            value={description}
            onChange={(event) => setDescription(event.target.value)}
            disabled={isFieldsLocked}
            className="mt-1 h-28 w-full resize-y rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 disabled:cursor-not-allowed disabled:opacity-60 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
          />
        </label>

        <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Label
            <select
              value={label ?? ""}
              disabled={isFieldsLocked}
              onChange={(event) => {
                const v = event.target.value;
                setLabel(v === "" ? null : (v as PlannerTaskLabel));
              }}
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 disabled:cursor-not-allowed disabled:opacity-60 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            >
              <option value="">None</option>
              <option value="Studio">Studio</option>
              <option value="Photoshoot">Photoshoot</option>
              <option value="Social Media">Social Media</option>
            </select>
          </label>
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Assigned to
            <select
              value={assignedTo ?? ""}
              onChange={(event) => {
                const v = event.target.value;
                setAssignedTo(v === "" ? null : v);
              }}
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            >
              <option value="">Unassigned</option>
              {effectiveAssigneeOptions.map((u) => (
                <option key={u.id} value={u.id}>
                  {u.name}
                </option>
              ))}
            </select>
          </label>
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Client Name
            <input
              value={clientName}
              onChange={(event) => setClientName(event.target.value)}
              placeholder="Wolt / Real Estate / etc."
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            />
          </label>
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Total Fee (EUR)
            <input
              type="number"
              min="0"
              step="0.01"
              value={totalFeeInput}
              onChange={(event) => setTotalFeeInput(event.target.value)}
              placeholder="0.00"
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            />
          </label>
        </div>

        <div className="mt-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">Sub-tasks</p>
          <div className="mt-2 space-y-2">
            {subtasks.map((subtask) => (
              <div
                key={subtask.id}
                className="flex items-center justify-between gap-2 rounded-lg border border-zinc-300 bg-zinc-50 px-2 py-2 dark:border-zinc-700 dark:bg-zinc-800/70"
              >
                <label className="flex min-w-0 flex-1 items-center gap-2 text-sm text-zinc-800 dark:text-zinc-100">
                  <input
                    type="checkbox"
                    checked={subtask.isCompleted}
                    onChange={() =>
                      setSubtasks((prev) =>
                        prev.map((item) =>
                          item.id === subtask.id ? { ...item, isCompleted: !item.isCompleted } : item
                        )
                      )
                    }
                    className="h-4 w-4 shrink-0 rounded border-zinc-400 disabled:opacity-50"
                  />
                  <input
                    value={subtask.title}
                    onChange={(event) =>
                      setSubtasks((prev) =>
                        prev.map((item) =>
                          item.id === subtask.id ? { ...item, title: event.target.value } : item
                        )
                      )
                    }
                    className={`min-w-0 flex-1 rounded border border-transparent bg-transparent px-1 py-0.5 text-sm outline-none focus:border-zinc-300 disabled:cursor-not-allowed disabled:opacity-60 dark:focus:border-zinc-600 ${
                      subtask.isCompleted ? "text-zinc-500 line-through opacity-60" : ""
                    }`}
                  />
                </label>
                {subtask.isStandard ? null : (
                  <button
                    type="button"
                    onClick={() => setSubtasks((prev) => prev.filter((item) => item.id !== subtask.id))}
                    className="rounded-md px-2 py-1 text-xs font-semibold text-red-600 hover:bg-red-50 dark:text-red-300 dark:hover:bg-red-900/30"
                    aria-label={`Delete sub-task ${subtask.title}`}
                  >
                    🗑
                  </button>
                )}
              </div>
            ))}
          </div>
          <div className="mt-2 flex gap-2">
            <input
              value={newSubtaskText}
              onChange={(event) => setNewSubtaskText(event.target.value)}
              placeholder="Add sub-task"
              className="w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            />
            <button
              type="button"
              onClick={handleAddSubtask}
              className="inline-flex h-10 items-center justify-center rounded-lg bg-zinc-900 px-4 text-sm font-semibold text-white transition hover:bg-zinc-700 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-300"
            >
              Add
            </button>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Due Date
            <input
              type="datetime-local"
              value={dueDateInput}
              onChange={(event) => setDueDateInput(event.target.value)}
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            />
          </label>
          <label className="block text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Repeat
            <select
              value={recurringType}
              onChange={(event) => setRecurringType(event.target.value as "none" | "daily" | "weekly" | "monthly")}
              className="mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            >
              <option value="none">None</option>
              <option value="daily">Daily</option>
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
            </select>
          </label>
        </div>

        <div className="mt-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
            Finished File Locations
          </p>
          <div
            onDragEnter={handleFileDropzoneDragEnter}
            onDragOver={handleFileDropzoneDragOver}
            onDragLeave={handleFileDropzoneDragLeave}
            onDrop={handleFileDropzoneDrop}
            className={`mt-1 rounded-lg border-2 border-dashed p-3 transition-colors ${
              isFileDropzoneActive
                ? "border-blue-500 bg-blue-50/10 dark:bg-blue-950/20"
                : "border-zinc-300 bg-zinc-50/50 dark:border-zinc-700 dark:bg-zinc-800/40"
            }`}
          >
            <div className="space-y-2">
              {(fileLocations.length > 0 ? fileLocations : [""]).map((location, index) => (
                <div key={`file-location-${index}`} className="flex items-center gap-2">
                  <input
                    value={location}
                    onChange={(event) => handleUpdateLocation(index, event.target.value)}
                    placeholder="Drag a file/folder (Electron) or paste a local folder path / URL"
                    className="w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 outline-none ring-zinc-400 focus:ring-2 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
                  />
                  <button
                    type="button"
                    onClick={() => handleRemoveLocation(index)}
                    className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-zinc-300 text-sm font-bold text-zinc-700 transition hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
                    aria-label="Remove location"
                    title="Remove location"
                  >
                    x
                  </button>
                </div>
              ))}
            </div>
            <button
              type="button"
              onClick={handleAddLocation}
              className="mt-2 inline-flex h-8 items-center justify-center rounded-md border border-zinc-300 px-3 text-xs font-semibold text-zinc-700 transition hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
            >
              + Add Location
            </button>
            <p className="mt-2 text-xs text-zinc-500 dark:text-zinc-400">
              In the desktop app, dropping a file captures its folder path automatically. In the browser, type or paste
              the path manually.
            </p>
          </div>
        </div>

        <div className="mt-4 rounded-lg border border-zinc-300 bg-zinc-50 px-3 py-2 text-xs text-zinc-600 dark:border-zinc-700 dark:bg-zinc-800/70 dark:text-zinc-300">
          {!isCreateMode && task?.status === "completed" ? (
            <div className="space-y-1">
              <p>
                Total time: <span className="font-semibold">{task.totalTimeLabel || "N/A"}</span>
              </p>
              <p className="truncate">
                Finished files:{" "}
                <span className="font-semibold">
                  {task.fileLocations.length > 0 ? task.fileLocations.join(" | ") : "Not provided"}
                </span>
              </p>
            </div>
          ) : (
            <p>
              Current elapsed:{" "}
              <span className="font-semibold">
                {Math.floor((task?.elapsedSeconds ?? 0) / 3600)}h {Math.floor(((task?.elapsedSeconds ?? 0) % 3600) / 60)}m
              </span>
            </p>
          )}
        </div>

        {!isCreateMode && task ? (
          <div className="mt-4">
            <button
              type="button"
              onClick={() => void handleOpenReviewBoard()}
              disabled={openingReviewBoard}
              className="inline-flex h-11 w-full items-center justify-center rounded-lg border border-violet-400/70 bg-violet-600 px-4 text-sm font-semibold text-white shadow-md transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {openingReviewBoard ? "Opening review board…" : "🎨 Open Review Board"}
            </button>
          </div>
        ) : null}

        <div className="mt-6 flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:justify-end">
          <button
            type="button"
            onClick={handleSaveAsTemplate}
            disabled={isFieldsLocked}
            className="inline-flex h-10 items-center justify-center rounded-lg border border-zinc-300 px-4 text-sm font-medium text-zinc-700 transition hover:bg-zinc-100 disabled:cursor-not-allowed disabled:opacity-50 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800"
          >
            Save as Template
          </button>
          {!isCreateMode && task?.status === "processing" && !task.isPaused ? (
            <button
              type="button"
              onClick={() => onPauseTask(task.id)}
              className="inline-flex h-10 items-center justify-center rounded-lg border border-amber-300 px-4 text-sm font-semibold text-amber-700 transition hover:bg-amber-50 dark:border-amber-700 dark:text-amber-200 dark:hover:bg-amber-900/30"
            >
              Pause Task
            </button>
          ) : null}
          {!isCreateMode && task?.status === "processing" && task.isPaused ? (
            <button
              type="button"
              onClick={() => onResumeTask(task.id)}
              className="inline-flex h-10 items-center justify-center rounded-lg border border-emerald-300 px-4 text-sm font-semibold text-emerald-700 transition hover:bg-emerald-50 dark:border-emerald-700 dark:text-emerald-200 dark:hover:bg-emerald-900/30"
            >
              Resume Task
            </button>
          ) : null}
          {!isCreateMode && task ? (
            <button
              type="button"
              onClick={() => {
                onDelete(task.id);
                onClose();
              }}
              className="inline-flex h-10 items-center justify-center rounded-lg border border-red-300 px-4 text-sm font-semibold text-red-600 transition hover:bg-red-50 dark:border-red-800 dark:text-red-300 dark:hover:bg-red-900/30"
            >
              Delete Task
            </button>
          ) : null}
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-10 items-center justify-center rounded-lg border border-zinc-300 px-4 text-sm font-medium text-zinc-700 transition hover:bg-zinc-100 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            className="inline-flex h-10 items-center justify-center rounded-lg bg-zinc-900 px-4 text-sm font-semibold text-white transition hover:bg-zinc-700 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-300"
          >
            {isCreateMode ? "Create Task" : "Save Changes"}
          </button>
        </div>
      </div>
    </div>
  );
}
