"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@supabase/supabase-js";

import { getAuthRole } from "@/lib/server/getAuthRole";

function createPhotoshootReviewSubtasksJson(): Array<{ title: string; completed: boolean }> {
  return [
    { title: "Review", completed: false },
    { title: "Editing", completed: false },
    { title: "Edited", completed: false },
    { title: "Send Email", completed: false },
    { title: "Completed", completed: false },
  ];
}

function serviceSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim();
  const key = serviceKey || anonKey;
  if (!url || !key) {
    return null;
  }
  return createClient(url, key, { auth: { persistSession: false } });
}

const KANBAN_READY_FOR_REVIEW = "Ready for Review";
const KANBAN_EDITING = "Editing";
const KANBAN_COMPLETED = "Completed";

export type SyncResult = { ok: true } | { ok: false; error: string };

/**
 * After Kanban (tasks) status changes: auto-create planner row or complete linked planner task.
 */
export async function syncKanbanPhotoshootStatus(input: {
  photoshootId: string;
  newStatusLabel: string;
  photoshootDisplayName: string;
}): Promise<SyncResult> {
  const auth = await getAuthRole();
  if (!auth.authenticated) {
    return { ok: false, error: "Unauthorized" };
  }

  const supabase = serviceSupabase();
  if (!supabase) {
    return { ok: false, error: "Database is not configured." };
  }

  const { photoshootId, newStatusLabel, photoshootDisplayName } = input;
  const id = photoshootId.trim();
  if (!id) {
    return { ok: false, error: "Missing photoshoot id." };
  }

  if (newStatusLabel === KANBAN_READY_FOR_REVIEW) {
    const { data: existing, error: selErr } = await supabase
      .from("studio_tasks")
      .select("id")
      .eq("photoshoot_id", id)
      .maybeSingle();

    if (selErr) {
      console.error("[agency-sync] studio_tasks select", selErr);
      return { ok: false, error: selErr.message };
    }

    if (!existing) {
      const name = photoshootDisplayName.trim() || "Photoshoot";
      const title = `Review Photoshoot: ${name}`;
      const subtasks = createPhotoshootReviewSubtasksJson();

      const { error: insErr } = await supabase.from("studio_tasks").insert({
        title,
        description: "",
        status: "planning",
        photoshoot_id: id,
        is_auto_generated: true,
        label: "Photoshoot",
        file_path: null,
        elapsed_seconds: 0,
        started_at: null,
        total_time_label: null,
        completed_at: null,
        due_date: null,
        recurring_type: "none",
        subtasks,
        assigned_users: [],
        assigned_to: null,
        order_index: 999999,
      });

      if (insErr) {
        console.error("[agency-sync] studio_tasks insert", insErr);
        return { ok: false, error: insErr.message };
      }
    }
  }

  if (newStatusLabel === KANBAN_COMPLETED) {
    const nowIso = new Date().toISOString();
    const { error: upErr } = await supabase
      .from("studio_tasks")
      .update({
        status: "completed",
        completed_at: nowIso,
      })
      .eq("photoshoot_id", id);

    if (upErr) {
      console.error("[agency-sync] studio_tasks complete from kanban", upErr);
      return { ok: false, error: upErr.message };
    }
  }

  revalidatePath("/planner");
  return { ok: true };
}

/**
 * When an auto-generated planner task moves to Processing, move linked Kanban shoot to Editing.
 */
export async function syncPlannerAutoTaskToKanban(input: {
  isAutoGenerated: boolean;
  photoshootId: string | null;
  previousStatus: string;
  newStatus: string;
}): Promise<SyncResult> {
  const auth = await getAuthRole();
  if (!auth.authenticated) {
    return { ok: false, error: "Unauthorized" };
  }

  if (!input.isAutoGenerated || !input.photoshootId?.trim()) {
    return { ok: true };
  }

  const prev = input.previousStatus.trim().toLowerCase();
  const next = input.newStatus.trim().toLowerCase();

  if (next !== "processing" || prev === "processing") {
    return { ok: true };
  }

  const supabase = serviceSupabase();
  if (!supabase) {
    return { ok: false, error: "Database is not configured." };
  }

  const { error } = await supabase
    .from("tasks")
    .update({ status: KANBAN_EDITING })
    .eq("id", input.photoshootId.trim());

  if (error) {
    console.error("[agency-sync] tasks -> Editing from planner", error);
    return { ok: false, error: error.message };
  }

  revalidatePath("/");
  revalidatePath("/kanban");
  revalidatePath("/planner");
  return { ok: true };
}
