"use client";

import Image from "next/image";
import { Pause, Play } from "lucide-react";
import { useEffect, useMemo, useRef, useState, Suspense, useCallback } from "react";
import PlannerStats from "@/app/components/PlannerStats";
import GlobalNavButtons from "@/app/components/GlobalNavButtons";
import GlobalLogoutControl from "@/app/components/GlobalLogoutControl";
import TaskAssigneeAvatars from "@/app/components/TaskAssigneeAvatars";
import { useAuthRole } from "@/app/contexts/AuthRoleContext";
import { usePlannerGlobalSafe } from "@/app/contexts/PlannerGlobalContext";
import { supabase } from "@/lib/supabaseClient";
import { syncPlannerAutoTaskToKanban } from "@/app/actions/agency-sync";
import { updateStudioTaskStatus } from "@/app/actions/studio-tasks";
import {
  appendCurrentUserIfMissing,
  parseAssignedUsers,
  serializeAssignedUsers,
  type PlannerAssignee,
} from "@/lib/plannerAssignees";
import {
  celebrateTaskCompletion,
  buildRandomDailyCompletionMessage,
} from "@/lib/taskCompletionCelebration";
import { countPlannerTodayCompletions } from "@/lib/kanbanDailyStreak";
import DailyStreakBadge from "@/app/components/DailyStreakBadge";
import PlannerTaskModal, {
  createStandardPlannerSubtasks,
  STD_COMPLETED_ID,
  STD_PREPARE_ID,
  STD_TODO_ID,
  type PlannerModalSaveInput,
  type PlannerSubTask,
  type PlannerTaskLabel,
  type PlannerTemplateOption,
} from "./components/PlannerTaskModal";
import PlannerCompletionPathModal from "./components/PlannerCompletionPathModal";
import PlannerPauseTaskModal from "./components/PlannerPauseTaskModal";

type MoveTaskOptions = {
  startNowFromMaster?: boolean;
  subtasks?: PlannerSubTask[];
  assignedUsers?: PlannerAssignee[];
  filePath?: string;
};

type PlannerStatusKey = "master" | "planning" | "processing" | "completed";
type PlannerColumnKey = Exclude<PlannerStatusKey, "master">;
type PlannerDbStatus = PlannerStatusKey | "template";
type RecurringType = "none" | "daily" | "weekly" | "monthly";

type PlannerTask = {
  id: string;
  title: string;
  description: string;
  status: PlannerStatusKey;
  subtasks: PlannerSubTask[];
  assignedUsers: PlannerAssignee[];
  assignedTo: string | null;
  label: PlannerTaskLabel;
  isAutoGenerated: boolean;
  photoshootId: string | null;
  startedAtSec: number | null;
  elapsedSeconds: number;
  isPaused: boolean;
  pauseNotes: string;
  filePath: string;
  totalTimeLabel: string;
  completedAt: string | null;
  dueDate: string | null;
  orderIndex: number;
  recurringType: RecurringType;
};

type PlannerBoardState = Record<PlannerStatusKey, PlannerTask[]>;
type ProfileRow = {
  id: string;
  email: string | null;
  full_name: string | null;
};

type StudioTaskRow = {
  id: string;
  title: string | null;
  description: string | null;
  status: string | null;
  file_path: string | null;
  pause_reason: string | null;
  elapsed_seconds: number | null;
  started_at: string | null;
  total_time_label: string | null;
  completed_at: string | null;
  due_date: string | null;
  recurring_type: string | null;
  subtasks: unknown;
  assigned_users?: unknown;
  assigned_to?: string | null;
  label?: string | null;
  is_auto_generated?: boolean | null;
  photoshoot_id?: string | null;
  order_index: number | null;
};

const COLUMN_CONFIG: Array<{ id: PlannerColumnKey; title: string }> = [
  { id: "planning", title: "Planning" },
  { id: "processing", title: "Processing" },
  { id: "completed", title: "Completed" },
];

const ALL_STATUSES: PlannerStatusKey[] = ["master", "planning", "processing", "completed"];

const EMPTY_BOARD: PlannerBoardState = {
  master: [],
  planning: [],
  processing: [],
  completed: [],
};

function normalizePlannerLabel(value: string | null | undefined): PlannerTaskLabel {
  const s = (value ?? "").trim();
  if (!s || s.toLowerCase() === "none") {
    return null;
  }
  if (s === "Studio" || s === "Photoshoot" || s === "Social Media") {
    return s;
  }
  return null;
}

function createTaskTitle(index: number): string {
  return `New Planner Task ${index}`;
}

function normalizeDbStatus(value: string | null | undefined): PlannerDbStatus {
  const normalized = (value ?? "").trim().toLowerCase();
  if (normalized === "template") {
    return "template";
  }
  return ALL_STATUSES.includes(normalized as PlannerStatusKey) ? (normalized as PlannerStatusKey) : "master";
}

function normalizePlannerStatus(value: string | null | undefined): PlannerStatusKey {
  const normalized = normalizeDbStatus(value);
  return normalized === "template" ? "master" : normalized;
}

function normalizeRecurringType(value: string | null | undefined): RecurringType {
  const normalized = (value ?? "").trim().toLowerCase();
  return normalized === "daily" || normalized === "weekly" || normalized === "monthly" ? normalized : "none";
}

function parseSubtasks(value: unknown, taskId: string): PlannerSubTask[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const result: PlannerSubTask[] = [];
  for (let index = 0; index < value.length; index += 1) {
    const candidate = value[index];
    if (!candidate || typeof candidate !== "object") {
      continue;
    }
    const candidateRecord = candidate as Record<string, unknown>;
    const id =
      typeof candidateRecord.id === "string" && candidateRecord.id.trim()
        ? candidateRecord.id
        : `${taskId}-sub-${index + 1}`;
    let title = typeof candidateRecord.title === "string" ? candidateRecord.title : "";
    if (!title.trim() && typeof candidateRecord.text === "string") {
      title = candidateRecord.text;
    }
    if (!title.trim()) {
      continue;
    }
    const fromFlag = Boolean(candidateRecord.isCompleted ?? candidateRecord.completed);
    const isStandardId = id === STD_PREPARE_ID || id === STD_TODO_ID || id === STD_COMPLETED_ID;
    const isStandard = Boolean(candidateRecord.isStandard) || isStandardId;
    result.push({
      id,
      title,
      isCompleted: fromFlag,
      isStandard,
    });
  }
  return result;
}

function sortSubtasksForDisplay(subtasks: PlannerSubTask[]): PlannerSubTask[] {
  const map = new Map(subtasks.map((s: PlannerSubTask) => [s.id, s]));
  const prepare = map.get(STD_PREPARE_ID);
  const todo = map.get(STD_TODO_ID);
  const completed = map.get(STD_COMPLETED_ID);
  const customs = subtasks.filter(
    (s: PlannerSubTask) =>
      s.id !== STD_PREPARE_ID && s.id !== STD_TODO_ID && s.id !== STD_COMPLETED_ID
  );
  const ordered: PlannerSubTask[] = [];
  if (prepare) {
    ordered.push(prepare);
  }
  if (todo) {
    ordered.push(todo);
  }
  ordered.push(...customs);
  if (completed) {
    ordered.push(completed);
  }
  return ordered;
}

function ensureStandardPlannerSubtasksOnTask(task: PlannerTask): PlannerTask {
  const byId = new Map(task.subtasks.map((s: PlannerSubTask) => [s.id, s]));
  const standards = createStandardPlannerSubtasks(task.title);
  const mergedStandards = standards.map((s: PlannerSubTask) => {
    const existing = byId.get(s.id);
    if (existing) {
      return { ...existing, isStandard: true };
    }
    return s;
  });
  const custom = task.subtasks.filter(
    (s: PlannerSubTask) => s.id !== STD_PREPARE_ID && s.id !== STD_TODO_ID && s.id !== STD_COMPLETED_ID
  );
  return { ...task, subtasks: sortSubtasksForDisplay([...mergedStandards, ...custom]) };
}

function isFinalStandardCompleted(subtasks: PlannerSubTask[]): boolean {
  return Boolean(subtasks.find((s: PlannerSubTask) => s.id === STD_COMPLETED_ID)?.isCompleted);
}

function isActiveOnMasterList(task: PlannerTask): boolean {
  if (task.status === "completed") {
    return false;
  }
  if (isFinalStandardCompleted(task.subtasks)) {
    return false;
  }
  return true;
}

function normalizeNewTaskSubtasks(payload: PlannerModalSaveInput, title: string): PlannerSubTask[] {
  const fromPayload = payload.subtasks;
  const hasAllStd = [STD_PREPARE_ID, STD_TODO_ID, STD_COMPLETED_ID].every((id) =>
    fromPayload.some((s: PlannerSubTask) => s.id === id)
  );
  if (hasAllStd) {
    return sortSubtasksForDisplay(
      fromPayload.map((s: PlannerSubTask) => ({
        ...s,
        isStandard: s.isStandard || [STD_PREPARE_ID, STD_TODO_ID, STD_COMPLETED_ID].includes(s.id),
      }))
    );
  }
  const base = createStandardPlannerSubtasks(title);
  const customs = fromPayload.filter(
    (s: PlannerSubTask) => s.id !== STD_PREPARE_ID && s.id !== STD_TODO_ID && s.id !== STD_COMPLETED_ID
  );
  return sortSubtasksForDisplay([...base, ...customs.map((c: PlannerSubTask) => ({ ...c, isStandard: false }))]);
}

function subtasksForRecurringSpawn(task: PlannerTask): PlannerSubTask[] {
  const customs = task.subtasks.filter((s: PlannerSubTask) => !s.isStandard);
  return sortSubtasksForDisplay([
    ...createStandardPlannerSubtasks(task.title),
    ...customs.map((c: PlannerSubTask) => ({ ...c, isCompleted: false })),
  ]);
}

function isPlannerTimerRunning(task: PlannerTask): boolean {
  return task.status === "processing" && !task.isPaused && task.startedAtSec !== null;
}

function profileRowToAssignee(row: ProfileRow): PlannerAssignee {
  const name = row.full_name?.trim() || row.email?.trim() || row.id;
  return { id: row.id, name };
}

function mapRowToTask(row: StudioTaskRow): PlannerTask {
  const startedAtMs = row.started_at ? new Date(row.started_at).getTime() : Number.NaN;
  const startedAtSec = Number.isFinite(startedAtMs) ? Math.floor(startedAtMs / 1000) : null;
  const status = normalizePlannerStatus(row.status);
  const elapsedSeconds = Math.max(0, row.elapsed_seconds ?? 0);
  const isPaused = status === "processing" && startedAtSec === null && elapsedSeconds > 0;

  const baseTask: PlannerTask = {
    id: String(row.id),
    title: row.title ?? "Untitled Task",
    description: row.description ?? "",
    status,
    subtasks: sortSubtasksForDisplay(parseSubtasks(row.subtasks, String(row.id))),
    assignedUsers: parseAssignedUsers(row.assigned_users),
    assignedTo: row.assigned_to?.trim() ? row.assigned_to.trim() : null,
    label: normalizePlannerLabel(row.label),
    isAutoGenerated: Boolean(row.is_auto_generated),
    photoshootId: row.photoshoot_id != null && String(row.photoshoot_id).trim() ? String(row.photoshoot_id) : null,
    startedAtSec,
    elapsedSeconds,
    isPaused,
    pauseNotes: row.pause_reason?.trim() ?? "",
    filePath: row.file_path ?? "",
    totalTimeLabel: row.total_time_label ?? "",
    completedAt: row.completed_at ?? null,
    dueDate: row.due_date ?? null,
    orderIndex: row.order_index ?? 0,
    recurringType: normalizeRecurringType(row.recurring_type),
  };
  return ensureStandardPlannerSubtasksOnTask(baseTask);
}

export default function PlannerPage() {
  const { authenticated, isLoading: authLoading } = useAuthRole();
  const [board, setBoard] = useState<PlannerBoardState>(EMPTY_BOARD);
  const [collapsedColumns, setCollapsedColumns] = useState<Partial<Record<PlannerColumnKey, boolean>>>({});
  const [activeDropColumn, setActiveDropColumn] = useState<PlannerColumnKey | null>(null);
  const [draggingTaskId, setDraggingTaskId] = useState<string | null>(null);
  const [sourceColumn, setSourceColumn] = useState<PlannerStatusKey | null>(null);
  const [suppressCardClicks, setSuppressCardClicks] = useState(false);
  const [taskCounter, setTaskCounter] = useState(1);
  const [activeTaskId, setActiveTaskId] = useState<string | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [templates, setTemplates] = useState<PlannerTemplateOption[]>([]);
  const [clockSec, setClockSec] = useState(() => Math.floor(Date.now() / 1000));
  const [loadingTasks, setLoadingTasks] = useState(true);
  const [persistenceError, setPersistenceError] = useState<string | null>(null);
  const [completionMessage, setCompletionMessage] = useState<string | null>(null);
  const [pathModalTaskId, setPathModalTaskId] = useState<string | null>(null);
  const [pendingCompletionOptions, setPendingCompletionOptions] = useState<
    Omit<MoveTaskOptions, "filePath"> | undefined
  >(undefined);
  const [filePathInputValue, setFilePathInputValue] = useState("");
  const [isSavingCompletionPath, setIsSavingCompletionPath] = useState(false);
  const [pausingTaskId, setPausingTaskId] = useState<string | null>(null);
  const [pauseNotes, setPauseNotes] = useState("");
  const [pauseFilePath, setPauseFilePath] = useState("");
  const [isSavingPause, setIsSavingPause] = useState(false);
  const [plannerUserId, setPlannerUserId] = useState<string | null>(null);
  const [profileAssignees, setProfileAssignees] = useState<PlannerAssignee[]>([]);
  const [masterListSubtaskDraft, setMasterListSubtaskDraft] = useState<Record<string, string>>({});
  const [masterListSubtasksExpanded, setMasterListSubtasksExpanded] = useState<Record<string, boolean>>({});
  const boardRef = useRef(board);
  boardRef.current = board;

  useEffect(() => {
    const timer = window.setInterval(() => {
      setClockSec(Math.floor(Date.now() / 1000));
    }, 1000);
    return () => window.clearInterval(timer);
  }, []);

  useEffect(() => {
    if (!completionMessage) {
      return;
    }
    const timer = window.setTimeout(() => {
      setCompletionMessage(null);
    }, 4000);
    return () => {
      window.clearTimeout(timer);
    };
  }, [completionMessage]);

  useEffect(() => {
    let isMounted = true;

    const loadTasks = async () => {
      if (!supabase) {
        if (isMounted) {
          setPersistenceError("Supabase is not configured. Planner changes will not persist.");
          setLoadingTasks(false);
        }
        return;
      }

      setLoadingTasks(true);
      setPersistenceError(null);

      const { data: authData } = await supabase.auth.getUser();
      const uid = authData.user?.id ?? null;
      if (isMounted) {
        setPlannerUserId(uid);
      }

      const [tasksResult, profilesResult] = await Promise.all([
        supabase.from("studio_tasks").select("*").order("order_index", { ascending: true }),
        supabase.from("profiles").select("id, email, full_name"),
      ]);

      if (!isMounted) {
        return;
      }

      const { data, error } = tasksResult;
      if (profilesResult.error) {
        console.warn("[planner] profiles:", profilesResult.error.message);
        if (isMounted) {
          setProfileAssignees([]);
        }
      } else {
        const profileRows = (profilesResult.data ?? []) as ProfileRow[];
        const assignees = [...profileRows]
          .map(profileRowToAssignee)
          .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" }));
        if (isMounted) {
          setProfileAssignees(assignees);
        }
      }

      if (error) {
        setPersistenceError(`Could not load planner tasks: ${error.message}`);
        setLoadingTasks(false);
        return;
      }

      const rawRows = (data ?? []) as StudioTaskRow[];
      const rows = rawRows.filter((row) => {
        if (normalizeDbStatus(row.status) === "template") {
          return true;
        }
        const assigned = row.assigned_to;
        if (assigned == null || String(assigned).trim() === "") {
          return true;
        }
        if (!uid) {
          return false;
        }
        return String(assigned) === uid;
      });

      const nextBoard: PlannerBoardState = { master: [], planning: [], processing: [], completed: [] };
      const nextTemplates: PlannerTemplateOption[] = [];
      rows.forEach((row) => {
        const normalizedStatus = normalizeDbStatus(row.status);
        if (normalizedStatus === "template") {
          const mappedTemplate = mapRowToTask(row);
          nextTemplates.push({
            id: mappedTemplate.id,
            title: mappedTemplate.title,
            description: mappedTemplate.description,
            subtasks: mappedTemplate.subtasks,
            recurringType: mappedTemplate.recurringType,
          });
          return;
        }
        const mapped = mapRowToTask(row);
        nextBoard[mapped.status].push(mapped);
      });

      setBoard(applyOrderIndexes(nextBoard));
      setTemplates(nextTemplates);
      setTaskCounter(rows.length + 1);
      setLoadingTasks(false);
    };

    void loadTasks();

    return () => {
      isMounted = false;
    };
  }, []);

  const taskLookup = useMemo(() => {
    const map = new Map<string, { task: PlannerTask; column: PlannerStatusKey }>();
    ALL_STATUSES.forEach((status) => {
      board[status].forEach((task) => {
        map.set(task.id, { task, column: status });
      });
    });
    return map;
  }, [board]);

  const dailyCompletionCount = useMemo(
    () => countPlannerTodayCompletions({ completed: board.completed }),
    [board.completed]
  );

  const currentPlannerMember = useMemo((): PlannerAssignee | null => {
    if (!plannerUserId) {
      return null;
    }
    const fromProfiles = profileAssignees.find((p) => p.id === plannerUserId);
    if (fromProfiles) {
      return fromProfiles;
    }
    return { id: plannerUserId, name: "You" };
  }, [plannerUserId, profileAssignees]);

  const formatDuration = (seconds: number): string => {
    const safe = Math.max(0, Math.floor(seconds));
    const hours = Math.floor(safe / 3600);
    const minutes = Math.floor((safe % 3600) / 60);
    return `${hours}h ${minutes}m`;
  };

  const toDbTimestamp = (sec: number | null): string | null => {
    if (!sec) {
      return null;
    }
    return new Date(sec * 1000).toISOString();
  };

  const calculateNextRecurringDueDate = (recurringType: RecurringType, fromIso: string): string | null => {
    if (recurringType === "none") {
      return null;
    }
    const base = new Date(fromIso);
    if (Number.isNaN(base.getTime())) {
      return null;
    }
    if (recurringType === "daily") {
      base.setDate(base.getDate() + 1);
    } else if (recurringType === "weekly") {
      base.setDate(base.getDate() + 7);
    } else if (recurringType === "monthly") {
      base.setMonth(base.getMonth() + 1);
    }
    return base.toISOString();
  };

  const syncOrderIndexes = async (nextBoard: PlannerBoardState) => {
    const client = supabase;
    if (!client) {
      throw new Error("Supabase is not configured.");
    }

    const orderedUpdates = ALL_STATUSES.flatMap((status) =>
      nextBoard[status].map((task, index) => ({
        id: task.id,
        status: task.status,
        order_index: index,
      }))
    ).filter((entry) => !entry.id.startsWith("temp-"));

    if (orderedUpdates.length === 0) {
      return;
    }

    const updates = orderedUpdates.map((entry) =>
      client
        .from("studio_tasks")
        .update({
          status: entry.status,
          order_index: entry.order_index,
        })
        .eq("id", entry.id)
    );

    const results = await Promise.all(updates);
    const failed = results.find((result) => result.error);
    if (failed?.error) {
      throw new Error(failed.error.message);
    }
  };

  const updateTaskInDb = async (
    taskId: string,
    updates: Partial<{
      title: string;
      description: string;
      status: PlannerStatusKey;
      file_path: string | null;
      pause_reason: string | null;
      elapsed_seconds: number;
      started_at: string | null;
      total_time_label: string | null;
      completed_at: string | null;
      due_date: string | null;
      recurring_type: RecurringType;
      subtasks: PlannerSubTask[];
      order_index: number;
      assigned_users: PlannerAssignee[];
      label: PlannerTaskLabel;
      assigned_to: string | null;
    }>
  ) => {
    if (!supabase) {
      throw new Error("Supabase is not configured.");
    }
    if (taskId.startsWith("temp-")) {
      return;
    }

    if (updates.status !== undefined) {
      const { status, ...rest } = updates;
      const res = await updateStudioTaskStatus(taskId, status, rest);
      if (!res.ok) {
        throw new Error(res.error);
      }
      return;
    }

    const { error } = await supabase.from("studio_tasks").update(updates).eq("id", taskId);
    if (error) {
      throw new Error(error.message);
    }
  };

  const getElapsedAt = (task: PlannerTask, nowSec: number): number => {
    if (!task.startedAtSec) {
      return task.elapsedSeconds;
    }
    return task.elapsedSeconds + Math.max(0, nowSec - task.startedAtSec);
  };

  function applyOrderIndexes(state: PlannerBoardState): PlannerBoardState {
    return {
      master: state.master.map((task, index) => ({ ...task, orderIndex: index })),
      planning: state.planning.map((task, index) => ({ ...task, orderIndex: index })),
      processing: state.processing.map((task, index) => ({ ...task, orderIndex: index })),
      completed: state.completed.map((task, index) => ({ ...task, orderIndex: index })),
    };
  }

  const updateSingleTask = (taskId: string, updater: (task: PlannerTask) => PlannerTask) => {
    setBoard((prev) => {
      const next = { ...prev };
      ALL_STATUSES.forEach((status) => {
        next[status] = next[status].map((task) => (task.id === taskId ? updater(task) : task));
      });
      return next;
    });
  };

  const moveTaskToStatus = (
    taskId: string,
    destinationStatus: PlannerStatusKey,
    options?: MoveTaskOptions
  ): Promise<void> => {
    const nowSec = clockSec;
    const location = taskLookup.get(taskId);
    if (!location) {
      return Promise.resolve();
    }
    const sourceStatus = location.column;
    if (sourceStatus === destinationStatus) {
      return Promise.resolve();
    }

    let nextTask: PlannerTask = { ...location.task, status: destinationStatus };

    if (options?.assignedUsers !== undefined) {
      nextTask = { ...nextTask, assignedUsers: options.assignedUsers };
    }

    if (options?.subtasks) {
      nextTask = { ...nextTask, subtasks: sortSubtasksForDisplay(options.subtasks) };
    }

    if (sourceStatus === "processing" && nextTask.startedAtSec && destinationStatus !== "processing") {
      nextTask = {
        ...nextTask,
        elapsedSeconds: getElapsedAt(nextTask, nowSec),
        startedAtSec: null,
      };
    }

    if (destinationStatus === "processing") {
      const shouldStartNow =
        options?.startNowFromMaster || (!nextTask.startedAtSec && !nextTask.isPaused && sourceStatus !== "completed");
      nextTask = {
        ...nextTask,
        startedAtSec: shouldStartNow ? nowSec : nextTask.startedAtSec,
        totalTimeLabel: "",
        completedAt: null,
      };
    }

    if (destinationStatus === "planning" && options?.startNowFromMaster) {
      nextTask = {
        ...nextTask,
        startedAtSec: nowSec,
        isPaused: false,
      };
    }

    if (destinationStatus === "completed") {
      const finalElapsed = getElapsedAt(nextTask, nowSec);
      const resolvedPath = (options?.filePath ?? nextTask.filePath).trim();
      nextTask = {
        ...nextTask,
        elapsedSeconds: finalElapsed,
        startedAtSec: null,
        isPaused: false,
        filePath: resolvedPath || nextTask.filePath,
        totalTimeLabel: formatDuration(finalElapsed),
        completedAt: new Date().toISOString(),
      };
    } else if (sourceStatus === "completed") {
      nextTask = {
        ...nextTask,
        completedAt: null,
      };
    }

    if (location.task.isAutoGenerated && destinationStatus === "processing") {
      nextTask = {
        ...nextTask,
        subtasks: nextTask.subtasks.map((s) =>
          s.id === STD_PREPARE_ID ? { ...s, isCompleted: true } : s
        ),
      };
    }
    if (location.task.isAutoGenerated && destinationStatus === "completed") {
      nextTask = {
        ...nextTask,
        subtasks: nextTask.subtasks.map((s) => ({ ...s, isCompleted: true })),
      };
    }

    let previousBoard: PlannerBoardState | null = null;
    const nextBoard = applyOrderIndexes({
      ...boardRef.current,
      [sourceStatus]: boardRef.current[sourceStatus].filter((task) => task.id !== taskId),
      [destinationStatus]: [nextTask, ...boardRef.current[destinationStatus]],
    });

    setBoard((prev) => {
      previousBoard = prev;
      return nextBoard;
    });

    return (async () => {
      try {
        const statusPayload: Parameters<typeof updateTaskInDb>[1] = {
          status: nextTask.status,
          started_at: toDbTimestamp(nextTask.startedAtSec),
          elapsed_seconds: nextTask.elapsedSeconds,
          file_path: nextTask.filePath || null,
          total_time_label: nextTask.totalTimeLabel || null,
          completed_at: nextTask.completedAt,
          recurring_type: nextTask.recurringType,
          subtasks: nextTask.subtasks,
          assigned_users: serializeAssignedUsers(nextTask.assignedUsers),
        };
        await updateTaskInDb(taskId, statusPayload);
        const kanbanSync = await syncPlannerAutoTaskToKanban({
          isAutoGenerated: location.task.isAutoGenerated,
          photoshootId: location.task.photoshootId,
          previousStatus: sourceStatus,
          newStatus: destinationStatus,
        });
        if (!kanbanSync.ok) {
          console.warn("[planner] agency sync:", kanbanSync.error);
        }
        await syncOrderIndexes(nextBoard);
        if (destinationStatus === "completed" && nextTask.recurringType !== "none") {
          const spawnBase = nextTask.completedAt ?? new Date().toISOString();
          const nextDueDate = calculateNextRecurringDueDate(nextTask.recurringType, spawnBase);
          createTaskOptimistically(
            "master",
            {
              title: nextTask.title,
              description: nextTask.description,
              subtasks: subtasksForRecurringSpawn(nextTask),
              dueDate: nextDueDate,
              filePath: "",
              recurringType: nextTask.recurringType,
              label: nextTask.label,
              assignedTo: nextTask.assignedTo,
            },
            { appendToBottom: true, initialOrderIndex: 999999 }
          );
        }
        if (destinationStatus === "completed") {
          const todayCompletionCount = countPlannerTodayCompletions(
            { completed: nextBoard.completed },
            { justCompletedTaskId: taskId }
          );
          celebrateTaskCompletion();
          setCompletionMessage(buildRandomDailyCompletionMessage(todayCompletionCount));
        } else {
          setCompletionMessage(null);
        }
        setPersistenceError(null);
      } catch (error) {
        if (previousBoard) {
          setBoard(previousBoard);
        }
        setCompletionMessage(null);
        setPersistenceError(error instanceof Error ? error.message : "Could not update planner task.");
        throw error;
      }
    })();
  };

  const closeCompletionPathModal = () => {
    setPathModalTaskId(null);
    setPendingCompletionOptions(undefined);
    setFilePathInputValue("");
    setIsSavingCompletionPath(false);
  };

  const requestTaskCompletion = (taskId: string, options?: Omit<MoveTaskOptions, "filePath">) => {
    const location = taskLookup.get(taskId);
    if (!location || location.column === "completed") {
      return;
    }
    setPathModalTaskId(taskId);
    setPendingCompletionOptions(options);
    setFilePathInputValue(location.task.filePath ?? "");
  };

  const handleSaveCompletionPath = async () => {
    if (!pathModalTaskId || isSavingCompletionPath) {
      return;
    }

    const taskId = pathModalTaskId;
    const saveOptions: MoveTaskOptions = {
      ...pendingCompletionOptions,
      filePath: filePathInputValue.trim(),
    };

    setIsSavingCompletionPath(true);
    try {
      await moveTaskToStatus(taskId, "completed", saveOptions);
      closeCompletionPathModal();
    } catch {
      setIsSavingCompletionPath(false);
    }
  };

  const clearDragState = () => {
    setDraggingTaskId(null);
    setSourceColumn(null);
    setActiveDropColumn(null);
    window.setTimeout(() => {
      setSuppressCardClicks(false);
    }, 140);
  };

  const handleDragStart = (taskId: string, columnId: PlannerStatusKey) => {
    setSuppressCardClicks(true);
    setDraggingTaskId(taskId);
    setSourceColumn(columnId);
  };

  const handleDrop = (destinationColumn: PlannerColumnKey) => {
    if (!draggingTaskId || !sourceColumn) {
      clearDragState();
      return;
    }
    if (sourceColumn === destinationColumn) {
      clearDragState();
      return;
    }

    const loc = taskLookup.get(draggingTaskId);
    let subtasksPatch: PlannerSubTask[] | undefined;
    if (loc && destinationColumn === "processing") {
      subtasksPatch = loc.task.subtasks.map((s) =>
        s.id === STD_PREPARE_ID ? { ...s, isCompleted: true } : s
      );
    } else if (loc && destinationColumn === "completed") {
      subtasksPatch = loc.task.subtasks.map((s) => ({ ...s, isCompleted: true }));
    }

    if (destinationColumn === "completed") {
      requestTaskCompletion(
        draggingTaskId,
        subtasksPatch ? { subtasks: subtasksPatch } : undefined
      );
      clearDragState();
      return;
    }

    moveTaskToStatus(
      draggingTaskId,
      destinationColumn,
      subtasksPatch ? { subtasks: subtasksPatch } : undefined
    );
    clearDragState();
  };

  const createTaskOptimistically = (
    targetStatus: "master" | "planning",
    payload: PlannerModalSaveInput,
    options?: { appendToBottom?: boolean; initialOrderIndex?: number }
  ) => {
    const tempId = `temp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const title = payload.title.trim() || createTaskTitle(taskCounter);
    const normalizedSubtasks = normalizeNewTaskSubtasks(payload, title);
    const nextTask: PlannerTask = {
      id: tempId,
      title,
      description: payload.description.trim(),
      status: targetStatus,
      subtasks: normalizedSubtasks,
      assignedUsers: [],
      assignedTo: payload.assignedTo ?? null,
      label: payload.label,
      isAutoGenerated: false,
      photoshootId: null,
      startedAtSec: null,
      elapsedSeconds: 0,
      isPaused: false,
      pauseNotes: "",
      filePath: payload.filePath.trim(),
      totalTimeLabel: "",
      completedAt: null,
      dueDate: payload.dueDate,
      orderIndex: options?.initialOrderIndex ?? 0,
      recurringType: payload.recurringType,
    };
    let previousBoard: PlannerBoardState | null = null;
    let optimisticBoard: PlannerBoardState | null = null;

    setTaskCounter((prev) => prev + 1);
    setBoard((prev) => {
      previousBoard = prev;
      const next = { ...prev };
      next[targetStatus] = options?.appendToBottom
        ? [...prev[targetStatus], nextTask]
        : [nextTask, ...prev[targetStatus]];
      const ordered = applyOrderIndexes(next);
      optimisticBoard = ordered;
      return ordered;
    });

    void (async () => {
      try {
        if (!supabase) {
          throw new Error("Supabase is not configured.");
        }
        const { data, error } = await supabase
          .from("studio_tasks")
          .insert({
            title,
            description: payload.description.trim(),
            status: targetStatus,
            file_path: payload.filePath.trim() || null,
            elapsed_seconds: 0,
            started_at: null,
            total_time_label: null,
            completed_at: null,
            due_date: payload.dueDate,
            recurring_type: payload.recurringType,
            subtasks: normalizedSubtasks,
            assigned_users: serializeAssignedUsers([]),
            label: payload.label,
            assigned_to: payload.assignedTo ?? null,
            is_auto_generated: false,
            photoshoot_id: null,
            order_index: options?.initialOrderIndex ?? 0,
          })
          .select("*")
          .single();

        if (error || !data) {
          throw new Error(error?.message ?? "Could not create planner task.");
        }

        const persistedTask = mapRowToTask(data as StudioTaskRow);
        let boardWithPersistedId: PlannerBoardState | null = null;
        setBoard((prev) => {
          const next: PlannerBoardState = {
            master: prev.master.map((task) => (task.id === tempId ? persistedTask : task)),
            planning: prev.planning.map((task) => (task.id === tempId ? persistedTask : task)),
            processing: prev.processing.map((task) => (task.id === tempId ? persistedTask : task)),
            completed: prev.completed.map((task) => (task.id === tempId ? persistedTask : task)),
          };
          const ordered = applyOrderIndexes(next);
          boardWithPersistedId = ordered;
          return ordered;
        });

        if (boardWithPersistedId) {
          await syncOrderIndexes(boardWithPersistedId);
        } else if (optimisticBoard) {
          await syncOrderIndexes(optimisticBoard);
        }
        setPersistenceError(null);
      } catch (error) {
        if (previousBoard) {
          setBoard(previousBoard);
        }
        setPersistenceError(error instanceof Error ? error.message : "Could not create planner task.");
      }
    })();
  };

  const openCreateTaskModal = () => {
    setActiveTaskId(null);
    setIsCreateModalOpen(true);
  };

  const handleCreateTask = (payload: PlannerModalSaveInput) => {
    createTaskOptimistically("master", payload, { appendToBottom: true, initialOrderIndex: 999999 });
  };

  const handleQuickAddPlanningTask = () => {
    createTaskOptimistically(
      "planning",
      {
        title: createTaskTitle(taskCounter),
        description: "New manual planner task. Click and edit details in future iteration.",
        subtasks: createStandardPlannerSubtasks(createTaskTitle(taskCounter)),
        dueDate: null,
        filePath: "",
        recurringType: "none",
        label: null,
        assignedTo: null,
      },
      { appendToBottom: true }
    );
  };

  const isColumnCollapsed = (columnId: PlannerColumnKey) => {
    const manuallySet = collapsedColumns[columnId];
    if (typeof manuallySet === "boolean") {
      return manuallySet;
    }
    return board[columnId].length === 0;
  };

  const toggleColumn = (columnId: PlannerColumnKey) => {
    const current = isColumnCollapsed(columnId);
    setCollapsedColumns((prev) => ({ ...prev, [columnId]: !current }));
  };

  const activeTask = useMemo(() => {
    if (!activeTaskId) {
      return null;
    }
    return taskLookup.get(activeTaskId)?.task ?? null;
  }, [activeTaskId, taskLookup]);

  const modalTaskPayload = useMemo(() => {
    if (isCreateModalOpen || !activeTask) {
      return null;
    }
    return {
      id: activeTask.id,
      title: activeTask.title,
      description: activeTask.description,
      subtasks: activeTask.subtasks,
      status: activeTask.status,
      isPaused: activeTask.isPaused,
      elapsedSeconds: activeTask.elapsedSeconds,
      startedAtSec: activeTask.startedAtSec,
      totalTimeLabel: activeTask.totalTimeLabel,
      filePath: activeTask.filePath,
      dueDate: activeTask.dueDate,
      recurringType: activeTask.recurringType,
      isAutoGenerated: activeTask.isAutoGenerated,
      label: activeTask.label,
      assignedTo: activeTask.assignedTo,
    };
  }, [isCreateModalOpen, activeTask]);

  const masterTasksSorted = useMemo(() => {
    const nowMs = clockSec * 1000;
    const oneDayMs = 24 * 60 * 60 * 1000;
    const isDueSoon = (dueDate: string | null) => {
      if (!dueDate) {
        return false;
      }
      const dueMs = new Date(dueDate).getTime();
      if (Number.isNaN(dueMs)) {
        return false;
      }
      const delta = dueMs - nowMs;
      return delta >= 0 && delta <= oneDayMs;
    };

    const pool = [...board.master, ...board.planning, ...board.processing].filter(isActiveOnMasterList);

    return pool.sort((a, b) => {
      const aPriority = isDueSoon(a.dueDate);
      const bPriority = isDueSoon(b.dueDate);
      if (aPriority !== bPriority) {
        return aPriority ? -1 : 1;
      }
      return a.orderIndex - b.orderIndex;
    });
  }, [board.master, board.planning, board.processing, clockSec]);

  const activeMasterListCount = useMemo(
    () => [...board.master, ...board.planning, ...board.processing].filter(isActiveOnMasterList).length,
    [board.master, board.planning, board.processing]
  );

  const closeTaskModal = () => {
    setActiveTaskId(null);
    setIsCreateModalOpen(false);
  };

  const handleSaveAsTemplate = (payload: PlannerModalSaveInput) => {
    const tempId = `temp-template-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const optimisticTemplate: PlannerTemplateOption = {
      id: tempId,
      title: payload.title.trim() || "Untitled Template",
      description: payload.description.trim(),
      subtasks: payload.subtasks,
      recurringType: payload.recurringType,
    };
    let previousTemplates: PlannerTemplateOption[] = [];
    setTemplates((prev) => {
      previousTemplates = prev;
      return [optimisticTemplate, ...prev];
    });

    void (async () => {
      try {
        if (!supabase) {
          throw new Error("Supabase is not configured.");
        }
        const { data, error } = await supabase
          .from("studio_tasks")
          .insert({
            title: payload.title.trim() || "Untitled Template",
            description: payload.description.trim(),
            status: "template",
            file_path: payload.filePath.trim() || null,
            elapsed_seconds: 0,
            started_at: null,
            total_time_label: null,
            completed_at: null,
            due_date: payload.dueDate,
            recurring_type: payload.recurringType,
            subtasks: payload.subtasks,
            assigned_users: serializeAssignedUsers([]),
            label: null,
            assigned_to: null,
            is_auto_generated: false,
            photoshoot_id: null,
            order_index: 999999,
          })
          .select("*")
          .single();

        if (error || !data) {
          throw new Error(error?.message ?? "Could not save template.");
        }

        const mappedTask = mapRowToTask(data as StudioTaskRow);
        const persistedTemplate: PlannerTemplateOption = {
          id: mappedTask.id,
          title: mappedTask.title,
          description: mappedTask.description,
          subtasks: mappedTask.subtasks,
          recurringType: mappedTask.recurringType,
        };
        setTemplates((prev) => prev.map((item) => (item.id === tempId ? persistedTemplate : item)));
        setPersistenceError(null);
      } catch (error) {
        setTemplates(previousTemplates);
        setPersistenceError(error instanceof Error ? error.message : "Could not save template.");
      }
    })();
  };

  const modalMode: "create" | "edit" = isCreateModalOpen ? "create" : "edit";
  const modalOpen = isCreateModalOpen || activeTask !== null;
  const modalKey = isCreateModalOpen ? "create-task" : activeTask?.id ?? "no-task";

  const updateTask = (taskId: string, updates: PlannerModalSaveInput) => {
    const loc = taskLookup.get(taskId);
    const effective: PlannerModalSaveInput =
      loc?.task.isAutoGenerated
        ? {
            ...updates,
            title: loc.task.title,
            description: loc.task.description,
            label: loc.task.label,
          }
        : updates;
    let previousBoard: PlannerBoardState | null = null;
    setBoard((prev) => {
      previousBoard = prev;
      const next = { ...prev };
      ALL_STATUSES.forEach((status) => {
        next[status] = next[status].map((task) =>
          task.id === taskId
            ? {
                ...task,
                title: effective.title,
                description: effective.description,
                subtasks: sortSubtasksForDisplay(effective.subtasks),
                dueDate: effective.dueDate,
                filePath: effective.filePath,
                recurringType: effective.recurringType,
                label: effective.label,
                assignedTo: effective.assignedTo,
              }
            : task
        );
      });
      return next;
    });

    void (async () => {
      try {
        await updateTaskInDb(taskId, {
          title: effective.title,
          description: effective.description,
          subtasks: sortSubtasksForDisplay(effective.subtasks),
          due_date: effective.dueDate,
          file_path: effective.filePath || null,
          recurring_type: effective.recurringType,
          label: effective.label,
          assigned_to: effective.assignedTo,
        });
        setPersistenceError(null);
      } catch (error) {
        if (previousBoard) {
          setBoard(previousBoard);
        }
        setPersistenceError(error instanceof Error ? error.message : "Could not save planner task changes.");
      }
    })();
  };

  const deleteTask = (taskId: string) => {
    let previousBoard: PlannerBoardState | null = null;
    let optimisticBoard: PlannerBoardState | null = null;
    setBoard((prev) => {
      previousBoard = prev;
      const next = { ...prev };
      ALL_STATUSES.forEach((status) => {
        next[status] = next[status].filter((task) => task.id !== taskId);
      });
      const ordered = applyOrderIndexes(next);
      optimisticBoard = ordered;
      return ordered;
    });
    setActiveTaskId((prev) => (prev === taskId ? null : prev));

    void (async () => {
      try {
        if (!taskId.startsWith("temp-")) {
          if (!supabase) {
            throw new Error("Supabase is not configured.");
          }
          const { error } = await supabase.from("studio_tasks").delete().eq("id", taskId);
          if (error) {
            throw new Error(error.message);
          }
        }
        if (optimisticBoard) {
          await syncOrderIndexes(optimisticBoard);
        }
        setPersistenceError(null);
      } catch (error) {
        if (previousBoard) {
          setBoard(previousBoard);
        }
        setPersistenceError(error instanceof Error ? error.message : "Could not delete planner task.");
      }
    })();
  };

  const persistTaskSubtasks = (taskId: string, nextSubtasks: PlannerSubTask[]) => {
    const loc = taskLookup.get(taskId);
    if (loc?.task.isAutoGenerated) {
      return;
    }
    const ordered = sortSubtasksForDisplay(nextSubtasks);
    let previousBoard: PlannerBoardState | null = null;
    setBoard((prev) => {
      previousBoard = prev;
      const next: PlannerBoardState = {
        master: prev.master.map((t) => (t.id === taskId ? { ...t, subtasks: ordered } : t)),
        planning: prev.planning.map((t) => (t.id === taskId ? { ...t, subtasks: ordered } : t)),
        processing: prev.processing.map((t) => (t.id === taskId ? { ...t, subtasks: ordered } : t)),
        completed: prev.completed.map((t) => (t.id === taskId ? { ...t, subtasks: ordered } : t)),
      };
      return applyOrderIndexes(next);
    });

    void (async () => {
      try {
        await updateTaskInDb(taskId, { subtasks: ordered });
        setPersistenceError(null);
      } catch (error) {
        if (previousBoard) {
          setBoard(previousBoard);
        }
        setPersistenceError(error instanceof Error ? error.message : "Could not save subtasks.");
      }
    })();
  };

  const onMasterPrepareToggle = (task: PlannerTask, checked: boolean) => {
    if (task.isAutoGenerated) {
      if (!checked) {
        return;
      }
      if (task.status === "completed" || task.status === "processing") {
        return;
      }
      moveTaskToStatus(task.id, "processing");
      return;
    }
    if (!checked) {
      const next = task.subtasks.map((s) => (s.id === STD_PREPARE_ID ? { ...s, isCompleted: false } : s));
      persistTaskSubtasks(task.id, next);
      return;
    }
    const next = task.subtasks.map((s) => (s.id === STD_PREPARE_ID ? { ...s, isCompleted: true } : s));
    if (task.status === "processing") {
      persistTaskSubtasks(task.id, next);
      return;
    }
    if (task.status === "completed") {
      return;
    }
    moveTaskToStatus(task.id, "processing", { subtasks: next });
  };

  const onMasterCompletedToggle = (task: PlannerTask, checked: boolean) => {
    if (task.isAutoGenerated) {
      if (!checked) {
        return;
      }
      if (task.status === "completed") {
        return;
      }
      requestTaskCompletion(task.id);
      return;
    }
    if (!checked) {
      const next = task.subtasks.map((s) => (s.id === STD_COMPLETED_ID ? { ...s, isCompleted: false } : s));
      persistTaskSubtasks(task.id, next);
      return;
    }
    const next = task.subtasks.map((s) => ({ ...s, isCompleted: true }));
    if (task.status === "completed") {
      persistTaskSubtasks(task.id, next);
      return;
    }
    requestTaskCompletion(task.id, { subtasks: next });
  };

  const onMasterListSubtaskToggle = (task: PlannerTask, subtask: PlannerSubTask, checked: boolean) => {
    if (subtask.id === STD_PREPARE_ID) {
      onMasterPrepareToggle(task, checked);
      return;
    }
    if (subtask.id === STD_COMPLETED_ID) {
      onMasterCompletedToggle(task, checked);
      return;
    }
    if (task.isAutoGenerated) {
      return;
    }
    const next = task.subtasks.map((s) => (s.id === subtask.id ? { ...s, isCompleted: checked } : s));
    persistTaskSubtasks(task.id, next);
  };

  const addCustomSubtaskFromMaster = (taskId: string, draft: string) => {
    const trimmed = draft.trim();
    if (!trimmed) {
      return;
    }
    const loc = taskLookup.get(taskId);
    if (!loc) {
      return;
    }
    const sorted = sortSubtasksForDisplay(loc.task.subtasks);
    const completedIdx = sorted.findIndex((s: PlannerSubTask) => s.id === STD_COMPLETED_ID);
    const newSub: PlannerSubTask = {
      id: `${taskId}-sub-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      title: trimmed,
      isCompleted: false,
      isStandard: false,
    };
    const next: PlannerSubTask[] =
      completedIdx === -1 ? [...sorted, newSub] : [...sorted.slice(0, completedIdx), newSub, ...sorted.slice(completedIdx)];
    persistTaskSubtasks(taskId, next);
    setMasterListSubtaskDraft((prev) => ({ ...prev, [taskId]: "" }));
  };

  const toggleMasterListSubtasksPanel = (taskId: string, task: PlannerTask) => {
    const expandedDefault = task.status === "processing" || task.status === "planning";
    const isOpen = masterListSubtasksExpanded[taskId] ?? expandedDefault;
    setMasterListSubtasksExpanded((prev) => ({ ...prev, [taskId]: !isOpen }));
  };

  const removeCustomSubtaskFromMaster = (taskId: string, subtaskId: string) => {
    const loc = taskLookup.get(taskId);
    if (!loc) {
      return;
    }
    const target = loc.task.subtasks.find((s) => s.id === subtaskId);
    if (target?.isStandard) {
      return;
    }
    const next = loc.task.subtasks.filter((s) => s.id !== subtaskId);
    persistTaskSubtasks(taskId, next);
  };

  const beginProcessingWithPrepareChecked = (taskId: string) => {
    const loc = taskLookup.get(taskId);
    if (!loc || loc.task.status === "completed") {
      return;
    }
    const nextAssignees = appendCurrentUserIfMissing(loc.task.assignedUsers, currentPlannerMember);
    const withPrepare = loc.task.subtasks.map((s) =>
      s.id === STD_PREPARE_ID ? { ...s, isCompleted: true } : s
    );
    moveTaskToStatus(taskId, "processing", {
      subtasks: withPrepare,
      assignedUsers: nextAssignees,
    });
  };

  const handleMasterListPlayClick = (task: PlannerTask) => {
    if (task.status === "processing" && task.isPaused) {
      resumeTask(task.id);
      return;
    }
    if (task.status === "processing" && isPlannerTimerRunning(task)) {
      return;
    }
    if (task.status === "processing") {
      const nowSec = Math.floor(Date.now() / 1000);
      const prepareDone = task.subtasks.some(
        (s) => s.id === STD_PREPARE_ID && s.isCompleted
      );
      const withPrepare = prepareDone
        ? task.subtasks
        : task.subtasks.map((s) =>
            s.id === STD_PREPARE_ID ? { ...s, isCompleted: true } : s
          );
      const ordered = sortSubtasksForDisplay(withPrepare);
      const nextAssignees = appendCurrentUserIfMissing(task.assignedUsers, currentPlannerMember);
      updateSingleTask(task.id, (t) => ({
        ...t,
        assignedUsers: nextAssignees,
        subtasks: ordered,
        startedAtSec: nowSec,
        isPaused: false,
      }));
      void (async () => {
        try {
          await updateTaskInDb(task.id, {
            started_at: toDbTimestamp(nowSec),
            subtasks: ordered,
            assigned_users: serializeAssignedUsers(nextAssignees),
          });
          setPersistenceError(null);
        } catch (error) {
          setPersistenceError(error instanceof Error ? error.message : "Could not start timer.");
        }
      })();
      return;
    }
    beginProcessingWithPrepareChecked(task.id);
  };

  const requestPauseTask = useCallback(
    (taskId: string) => {
      const latestTask = taskLookup.get(taskId)?.task;
      if (!latestTask || latestTask.status !== "processing" || latestTask.isPaused) {
        return;
      }
      setPausingTaskId(taskId);
      setPauseNotes(latestTask.pauseNotes ?? "");
      setPauseFilePath(latestTask.filePath ?? "");
    },
    [taskLookup]
  );

  const closePauseModal = () => {
    setPausingTaskId(null);
    setPauseNotes("");
    setPauseFilePath("");
    setIsSavingPause(false);
  };

  const handleConfirmPause = async () => {
    if (!pausingTaskId || isSavingPause) {
      return;
    }

    const taskId = pausingTaskId;
    const nowSec = Math.floor(Date.now() / 1000);
    const priorBoard = board;
    const latestTask = taskLookup.get(taskId)?.task;
    if (!latestTask || latestTask.status !== "processing" || latestTask.isPaused) {
      closePauseModal();
      return;
    }

    const trimmedNotes = pauseNotes.trim();
    const trimmedFilePath = pauseFilePath.trim();
    const elapsed = getElapsedAt(latestTask, nowSec);

    updateSingleTask(taskId, (task) => ({
      ...task,
      elapsedSeconds: elapsed,
      startedAtSec: null,
      isPaused: true,
      pauseNotes: trimmedNotes,
      filePath: trimmedFilePath || task.filePath,
    }));

    setIsSavingPause(true);
    try {
      await updateTaskInDb(taskId, {
        started_at: null,
        elapsed_seconds: elapsed,
        pause_reason: trimmedNotes || null,
        file_path: trimmedFilePath || latestTask.filePath || null,
      });
      setPersistenceError(null);
      closePauseModal();
    } catch (error) {
      setBoard(priorBoard);
      setPersistenceError(error instanceof Error ? error.message : "Could not pause planner task.");
      setIsSavingPause(false);
    }
  };

  const resumeTask = (taskId: string) => {
    const nowSec = Math.floor(Date.now() / 1000);
    const priorBoard = board;
    updateSingleTask(taskId, (task) => {
      if (task.status !== "processing" || !task.isPaused) {
        return task;
      }
      return {
        ...task,
        assignedUsers: appendCurrentUserIfMissing(task.assignedUsers, currentPlannerMember),
        startedAtSec: nowSec,
        isPaused: false,
      };
    });

    const latestTask = taskLookup.get(taskId)?.task;
    if (!latestTask || latestTask.status !== "processing" || !latestTask.isPaused) {
      return;
    }

    const mergedAssign = appendCurrentUserIfMissing(latestTask.assignedUsers, currentPlannerMember);

    void (async () => {
      try {
        await updateTaskInDb(taskId, {
          started_at: toDbTimestamp(nowSec),
          assigned_users: serializeAssignedUsers(mergedAssign),
        });
        setPersistenceError(null);
      } catch (error) {
        setBoard(priorBoard);
        setPersistenceError(error instanceof Error ? error.message : "Could not resume planner task.");
      }
    })();
  };

  const plannerGlobalSafe = usePlannerGlobalSafe();
  const setGlobalActiveTimer = plannerGlobalSafe?.setActiveTimerSession;
  const globalPauseHandlerRef = plannerGlobalSafe?.pauseHandlerRef;

  useEffect(() => {
    if (!globalPauseHandlerRef) {
      return;
    }
    globalPauseHandlerRef.current = requestPauseTask;
    return () => {
      globalPauseHandlerRef.current = null;
    };
  }, [globalPauseHandlerRef, requestPauseTask]);

  useEffect(() => {
    if (!setGlobalActiveTimer) {
      return;
    }
    const running =
      board.processing.find((t) => isPlannerTimerRunning(t)) ??
      [...board.master, ...board.planning, ...board.processing].find((t) => isPlannerTimerRunning(t));

    if (!running) {
      setGlobalActiveTimer(null);
      return;
    }

    const remaining = running.subtasks.filter((s) => !s.isCompleted).length;
    setGlobalActiveTimer({
      taskId: running.id,
      title: running.title,
      startedAtSec: running.startedAtSec,
      elapsedSeconds: running.elapsedSeconds,
      isPaused: running.isPaused,
      remainingSubtasks: remaining,
    });
  }, [board, clockSec, setGlobalActiveTimer]);

  return (
    <div className="relative min-h-screen bg-zinc-50 px-4 py-8 font-sans dark:bg-black sm:px-6 lg:px-8">
      <DailyStreakBadge count={dailyCompletionCount} />
      {completionMessage ? (
        <div
          role="status"
          aria-live="polite"
          className="pointer-events-none fixed left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 transform rounded-lg border border-green-500 bg-green-900 px-6 py-4 text-lg font-bold text-green-100 shadow-2xl"
        >
          {completionMessage}
        </div>
      ) : null}
      <main className="mx-auto w-full max-w-[1800px]">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex min-w-0 flex-1 items-start gap-3">
            <Image
              src="/logo.webp"
              alt="Workflow"
              width={480}
              height={132}
              className="mt-0.5 h-[132px] w-auto max-w-[min(600px,90vw)] shrink-0 object-contain"
              priority
            />
            <div className="min-w-0">
              <h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100 sm:text-3xl">
                Studio Planner
              </h1>
              <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
                Drag and drop tasks between stages to track studio planning work.
              </p>
              {loadingTasks ? (
                <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">Loading planner tasks...</p>
              ) : null}
              {persistenceError ? (
                <p className="mt-1 text-xs text-red-600 dark:text-red-400">{persistenceError}</p>
              ) : null}
            </div>
          </div>
          {!authLoading && authenticated ? (
            <div className="flex shrink-0 flex-wrap items-center justify-end gap-2 sm:max-w-[780px] sm:justify-end">
              <Suspense fallback={null}>
                <GlobalNavButtons className="flex flex-wrap items-center justify-end gap-2">
                  <GlobalLogoutControl />
                </GlobalNavButtons>
              </Suspense>
            </div>
          ) : null}
        </div>

        <PlannerStats
          completedTasks={board.completed.map((t) => ({
            completedAt: t.completedAt,
            elapsedSeconds: t.elapsedSeconds,
          }))}
        />

        <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
          <aside className="h-[70vh] rounded-xl border border-zinc-200 bg-white p-3 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
            <div className="mb-3 flex items-center justify-between">
              <h2 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Master To-Do List</h2>
              <span className="rounded-full bg-zinc-100 px-2 py-0.5 text-xs font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
                {activeMasterListCount}
              </span>
            </div>
            <button
              type="button"
              onClick={openCreateTaskModal}
              className="mb-3 inline-flex h-9 w-full items-center justify-center rounded-md border border-zinc-300 bg-white px-3 text-xs font-semibold text-zinc-700 transition hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200 dark:hover:bg-zinc-800"
            >
              Add Master Task
            </button>
            <div className="h-[calc(70vh-92px)] space-y-2 overflow-y-auto pr-1 [scrollbar-color:#4a4a4a_#000000] [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-black [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-zinc-600">
              {masterTasksSorted.map((task) => {
                const completedCount = task.subtasks.filter((subtask) => subtask.isCompleted).length;
                const totalCount = task.subtasks.length;
                const progress = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
                const nowMs = clockSec * 1000;
                const dueMs = task.dueDate ? new Date(task.dueDate).getTime() : Number.NaN;
                const isDueSoonCard =
                  Number.isFinite(dueMs) && dueMs >= nowMs && dueMs - nowMs <= 24 * 60 * 60 * 1000;
                const statusLabel =
                  task.status === "planning"
                    ? "Planning"
                    : task.status === "processing"
                      ? "Processing"
                      : null;
                const subtasksReadOnly = task.isAutoGenerated;
                const panelExpanded =
                  masterListSubtasksExpanded[task.id] ??
                  (task.status === "processing" || task.status === "planning");
                const orderedSubtasks = sortSubtasksForDisplay(task.subtasks);
                const prepareIsChecked = Boolean(
                  orderedSubtasks.find((s: PlannerSubTask) => s.id === STD_PREPARE_ID)?.isCompleted
                );
                const allExceptCompletedChecked = orderedSubtasks
                  .filter((s: PlannerSubTask) => s.id !== STD_COMPLETED_ID)
                  .every((s: PlannerSubTask) => s.isCompleted);
                return (
                  <article
                    key={task.id}
                    onClick={() => {
                      setIsCreateModalOpen(false);
                      setActiveTaskId(task.id);
                    }}
                    className="group cursor-pointer rounded-lg border border-zinc-300 bg-white p-3 shadow-sm dark:border-zinc-700 dark:bg-zinc-900"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex min-w-0 flex-1 items-start gap-1">
                        <button
                          type="button"
                          onClick={(event) => {
                            event.stopPropagation();
                            toggleMasterListSubtasksPanel(task.id, task);
                          }}
                          className="mt-0.5 shrink-0 rounded p-0.5 text-zinc-500 transition hover:bg-zinc-100 dark:hover:bg-zinc-800"
                          aria-expanded={panelExpanded}
                          aria-label={panelExpanded ? "Collapse subtasks" : "Expand subtasks"}
                        >
                          <span className="block text-[10px] font-medium leading-none text-zinc-600 dark:text-zinc-400">
                            {panelExpanded ? "▼" : "▶"}
                          </span>
                        </button>
                        <h3 className="min-w-0 text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                          {task.title}
                        </h3>
                      </div>
                      <div className="flex shrink-0 flex-wrap items-center justify-end gap-1">
                        <TaskAssigneeAvatars assignees={task.assignedUsers} />
                        {task.label ? (
                          <span className="text-xs font-medium text-zinc-400 dark:text-zinc-500">{task.label}</span>
                        ) : null}
                        {statusLabel ? (
                          <span className="rounded-full bg-zinc-100 px-2 py-0.5 text-[10px] font-semibold text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
                            {statusLabel}
                          </span>
                        ) : null}
                        {isDueSoonCard ? (
                          <span className="inline-flex items-center gap-1 rounded-full bg-orange-100 px-2 py-0.5 text-[10px] font-semibold text-orange-700 dark:bg-orange-900/40 dark:text-orange-200">
                            <span className="h-1.5 w-1.5 rounded-full bg-orange-500" />
                            Due Soon
                          </span>
                        ) : null}
                      </div>
                    </div>
                    <p className="mt-1 text-xs text-zinc-600 dark:text-zinc-400">{task.description}</p>
                    {task.dueDate ? (
                      <p className="mt-1 text-[11px] text-zinc-500 dark:text-zinc-400">
                        Due: {new Date(task.dueDate).toLocaleString()}
                      </p>
                    ) : null}
                    {totalCount > 0 ? (
                      <div className="mt-2">
                        <p className="text-[11px] font-medium text-zinc-500 dark:text-zinc-400">
                          {completedCount}/{totalCount} Sub-tasks
                        </p>
                        <div className="mt-1 h-1.5 w-full rounded-full bg-zinc-200 dark:bg-zinc-700">
                          <div
                            className="h-full rounded-full bg-zinc-900 transition-all dark:bg-zinc-100"
                            style={{ width: `${progress}%` }}
                          />
                        </div>
                      </div>
                    ) : null}
                    {panelExpanded ? (
                      <div
                        className="mt-2 space-y-1.5"
                        onClick={(event) => event.stopPropagation()}
                        onKeyDown={(event) => event.stopPropagation()}
                      >
                        {orderedSubtasks.map((subtask) => {
                          const isPrepareRow = subtask.id === STD_PREPARE_ID;
                          const isCompletedRow = subtask.id === STD_COMPLETED_ID;
                          const checkboxDisabled =
                            subtasksReadOnly ||
                            (isCompletedRow ? !allExceptCompletedChecked : !isPrepareRow && !prepareIsChecked);
                          const checkboxLockedClass = checkboxDisabled
                            ? "opacity-50 cursor-not-allowed"
                            : "cursor-pointer";
                          return (
                            <div
                              key={subtask.id}
                              className="flex items-start gap-2 rounded-md border border-zinc-200 bg-zinc-50/80 px-2 py-1.5 dark:border-zinc-700 dark:bg-zinc-800/50"
                            >
                              <input
                                type="checkbox"
                                checked={subtask.isCompleted}
                                disabled={checkboxDisabled}
                                onChange={(event) =>
                                  onMasterListSubtaskToggle(task, subtask, event.target.checked)
                                }
                                className={`mt-0.5 h-4 w-4 shrink-0 rounded border-zinc-400 ${checkboxLockedClass}`}
                              />
                              <input
                                value={subtask.title}
                                readOnly={subtasksReadOnly}
                                onChange={(event) => {
                                  if (subtasksReadOnly) {
                                    return;
                                  }
                                  const value = event.target.value;
                                  setBoard((prev) => {
                                    const patch = (tk: PlannerTask) =>
                                      tk.id !== task.id
                                        ? tk
                                        : {
                                            ...tk,
                                            subtasks: tk.subtasks.map((s) =>
                                              s.id === subtask.id ? { ...s, title: value } : s
                                            ),
                                          };
                                    return applyOrderIndexes({
                                      master: prev.master.map(patch),
                                      planning: prev.planning.map(patch),
                                      processing: prev.processing.map(patch),
                                      completed: prev.completed.map(patch),
                                    });
                                  });
                                }}
                                onBlur={() => {
                                  if (task.isAutoGenerated) {
                                    return;
                                  }
                                  const latest = ALL_STATUSES.flatMap((col) => boardRef.current[col]).find(
                                    (t) => t.id === task.id
                                  );
                                  if (!latest) {
                                    return;
                                  }
                                  void (async () => {
                                    try {
                                      await updateTaskInDb(task.id, {
                                        subtasks: sortSubtasksForDisplay(latest.subtasks),
                                      });
                                      setPersistenceError(null);
                                    } catch (error) {
                                      setPersistenceError(
                                        error instanceof Error ? error.message : "Could not save subtask text."
                                      );
                                    }
                                  })();
                                }}
                                className="min-w-0 flex-1 border-0 bg-transparent p-0 text-xs text-zinc-800 outline-none focus:ring-0 dark:text-zinc-100"
                              />
                              {subtask.isStandard || subtasksReadOnly ? null : (
                                <button
                                  type="button"
                                  onClick={() => removeCustomSubtaskFromMaster(task.id, subtask.id)}
                                  className="shrink-0 rounded px-1 text-xs text-red-600 hover:bg-red-50 dark:text-red-300 dark:hover:bg-red-900/30"
                                  aria-label={`Remove ${subtask.title}`}
                                >
                                  🗑
                                </button>
                              )}
                            </div>
                          );
                        })}
                        {subtasksReadOnly ? null : (
                        <div className="flex gap-1 pt-0.5">
                          <input
                            value={masterListSubtaskDraft[task.id] ?? ""}
                            onChange={(event) =>
                              setMasterListSubtaskDraft((prev) => ({
                                ...prev,
                                [task.id]: event.target.value,
                              }))
                            }
                            placeholder="Add custom subtask"
                            className="min-w-0 flex-1 rounded border border-zinc-200 bg-white px-2 py-1 text-xs text-zinc-800 outline-none dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"
                          />
                          <button
                            type="button"
                            onClick={() => addCustomSubtaskFromMaster(task.id, masterListSubtaskDraft[task.id] ?? "")}
                            className="shrink-0 rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white dark:bg-zinc-100 dark:text-zinc-900"
                          >
                            Add
                          </button>
                        </div>
                        )}
                      </div>
                    ) : null}
                    {isPlannerTimerRunning(task) ? (
                      <button
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation();
                          requestPauseTask(task.id);
                        }}
                        className="mt-3 inline-flex h-8 items-center justify-center gap-1.5 rounded-md border border-amber-200/90 px-3 text-xs font-semibold text-amber-900 opacity-0 transition group-hover:opacity-100 hover:border-amber-400 hover:bg-amber-50 dark:border-amber-800 dark:text-amber-100 dark:hover:border-amber-600 dark:hover:bg-amber-950/40"
                        aria-label="Pause time tracking"
                      >
                        <Pause className="h-3.5 w-3.5 shrink-0" strokeWidth={2} aria-hidden />
                        Pause
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation();
                          handleMasterListPlayClick(task);
                        }}
                        className="mt-3 inline-flex h-8 items-center justify-center gap-1.5 rounded-md border border-emerald-300 px-3 text-xs font-semibold text-emerald-700 opacity-0 transition group-hover:opacity-100 hover:bg-emerald-50 dark:border-emerald-700 dark:text-emerald-200 dark:hover:bg-emerald-900/30"
                        aria-label={
                          task.status === "processing" && task.isPaused
                            ? "Resume time tracking"
                            : "Start time tracking"
                        }
                      >
                        <Play className="h-3.5 w-3.5 shrink-0" strokeWidth={2} aria-hidden />
                        {task.status === "processing" && task.isPaused ? "Resume" : "Start"}
                      </button>
                    )}
                  </article>
                );
              })}
              {activeMasterListCount === 0 ? (
                <div className="rounded-lg border border-dashed border-zinc-300 p-4 text-center text-xs text-zinc-500 dark:border-zinc-700 dark:text-zinc-400">
                  No active master tasks.
                </div>
              ) : null}
            </div>
          </aside>

          <div className="overflow-x-auto pb-3 [scrollbar-color:#4a4a4a_#000000] [&::-webkit-scrollbar]:h-2 [&::-webkit-scrollbar-track]:bg-black [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:border [&::-webkit-scrollbar-thumb]:border-black [&::-webkit-scrollbar-thumb]:bg-zinc-600">
            <div className="flex min-w-max flex-nowrap gap-4">
              {COLUMN_CONFIG.map((column) => {
                const isActive = activeDropColumn === column.id;
                const isCollapsed = isColumnCollapsed(column.id);
                return (
                  <section
                    key={column.id}
                    onDragOver={(event) => {
                      event.preventDefault();
                      setActiveDropColumn(column.id);
                    }}
                    onDragLeave={() => setActiveDropColumn((prev) => (prev === column.id ? null : prev))}
                    onDrop={(event) => {
                      event.preventDefault();
                      handleDrop(column.id);
                    }}
                    className={`h-[70vh] shrink-0 rounded-xl border bg-white p-3 shadow-sm transition-all dark:bg-zinc-900 ${
                      isCollapsed ? "w-12" : "w-[300px]"
                    } ${
                      isActive
                        ? "border-zinc-500 bg-zinc-100/80 dark:border-zinc-500 dark:bg-zinc-800/80"
                        : "border-zinc-200 dark:border-zinc-800"
                    }`}
                  >
                    <div className={`mb-3 flex items-center ${isCollapsed ? "justify-center" : "justify-between"}`}>
                      {isCollapsed ? (
                        <h2 className="text-xs font-semibold text-zinc-800 dark:text-zinc-100 [writing-mode:vertical-rl] rotate-180">
                          {column.title}
                        </h2>
                      ) : (
                        <>
                          <h2 className="text-sm font-semibold text-zinc-800 dark:text-zinc-100">{column.title}</h2>
                          <span className="rounded-full bg-zinc-100 px-2 py-0.5 text-xs font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
                            {board[column.id].length}
                          </span>
                        </>
                      )}
                      <button
                        type="button"
                        onClick={() => toggleColumn(column.id)}
                        className="ml-1 rounded px-1 text-xs text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                        aria-label={isCollapsed ? "Expand column" : "Collapse column"}
                      >
                        {isCollapsed ? ">" : "<"}
                      </button>
                    </div>

                    {!isCollapsed ? (
                      <div className="h-[calc(70vh-62px)] space-y-2 overflow-y-auto pr-1 [scrollbar-color:#4a4a4a_#000000] [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-black [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-zinc-600">
                        {column.id === "planning" ? (
                          <button
                            type="button"
                            onClick={handleQuickAddPlanningTask}
                            className="inline-flex h-9 w-full items-center justify-center rounded-md border border-zinc-300 bg-white px-3 text-xs font-semibold text-zinc-700 transition hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200 dark:hover:bg-zinc-800"
                          >
                            Add Planning Task
                          </button>
                        ) : null}
                        {board[column.id].map((task) => {
                          const completedCount = task.subtasks.filter((subtask) => subtask.isCompleted).length;
                          const totalCount = task.subtasks.length;
                          const progress = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
                          const elapsedNow = getElapsedAt(task, clockSec);
                          return (
                            <article
                              key={task.id}
                              draggable
                              onDragStart={() => handleDragStart(task.id, column.id)}
                              onDragEnd={clearDragState}
                              onClick={() => {
                                if (suppressCardClicks) return;
                                setIsCreateModalOpen(false);
                                setActiveTaskId(task.id);
                              }}
                              className="cursor-grab rounded-lg border border-zinc-300 bg-white p-3 shadow-sm active:cursor-grabbing dark:border-zinc-700 dark:bg-zinc-900"
                            >
                              <div className="flex items-start justify-between gap-2">
                                <div className="min-w-0 flex-1">
                                  <h3 className="min-w-0 text-sm font-semibold leading-snug text-zinc-900 dark:text-zinc-100">
                                    {task.title}
                                  </h3>
                                  {task.label ? (
                                    <span className="mt-0.5 block text-xs font-medium text-zinc-400 dark:text-zinc-500">
                                      {task.label}
                                    </span>
                                  ) : null}
                                </div>
                                <TaskAssigneeAvatars assignees={task.assignedUsers} />
                              </div>
                              <p className="mt-1 text-xs text-zinc-600 dark:text-zinc-400">{task.description}</p>
                              {column.id === "processing" && task.isPaused ? (
                                <div className="mt-2 space-y-1">
                                  <span className="inline-flex rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-medium text-amber-700 dark:bg-amber-900/40 dark:text-amber-200">
                                    Paused
                                  </span>
                                  {task.pauseNotes ? (
                                    <p className="text-[11px] text-zinc-500 dark:text-zinc-400">{task.pauseNotes}</p>
                                  ) : null}
                                  {task.filePath ? (
                                    <p className="truncate text-[11px] text-zinc-500 dark:text-zinc-400">
                                      Link: {task.filePath}
                                    </p>
                                  ) : null}
                                </div>
                              ) : null}
                              {column.id === "processing" || column.id === "completed" ? (
                                <p className="mt-2 text-[11px] font-medium text-zinc-600 dark:text-zinc-300">
                                  {column.id === "completed"
                                    ? `Total: ${task.totalTimeLabel || formatDuration(task.elapsedSeconds)}`
                                    : `Elapsed: ${formatDuration(elapsedNow)}`}
                                </p>
                              ) : null}
                              {column.id === "completed" && task.filePath ? (
                                <p className="mt-1 truncate text-[11px] text-zinc-500 dark:text-zinc-400">
                                  File: {task.filePath}
                                </p>
                              ) : null}
                              {totalCount > 0 ? (
                                <div className="group relative mt-2">
                                  <p className="inline-flex rounded-full bg-zinc-100 px-2 py-0.5 text-[11px] font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
                                    {completedCount}/{totalCount} Sub-tasks
                                  </p>
                                  <div className="mt-1 h-1.5 w-full rounded-full bg-zinc-200 dark:bg-zinc-700">
                                    <div
                                      className="h-full rounded-full bg-zinc-900 transition-all dark:bg-zinc-100"
                                      style={{ width: `${progress}%` }}
                                    />
                                  </div>
                                  <div className="pointer-events-none absolute left-0 top-full z-[70] mt-2 hidden w-64 rounded-md border border-zinc-300 bg-white p-2 text-[11px] text-zinc-700 shadow-lg group-hover:block dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-200">
                                    {task.subtasks.map((subtask) => (
                                      <p
                                        key={subtask.id}
                                        className={`truncate py-0.5 ${subtask.isCompleted ? "opacity-60 line-through" : ""}`}
                                      >
                                        {subtask.title}
                                      </p>
                                    ))}
                                  </div>
                                </div>
                              ) : null}
                            </article>
                          );
                        })}
                      </div>
                    ) : null}
                  </section>
                );
              })}
            </div>
          </div>
        </div>
      </main>
      <PlannerPauseTaskModal
        isOpen={pausingTaskId !== null}
        pauseNotes={pauseNotes}
        pauseFilePath={pauseFilePath}
        isSaving={isSavingPause}
        onPauseNotesChange={setPauseNotes}
        onPauseFilePathChange={setPauseFilePath}
        onConfirmPause={() => void handleConfirmPause()}
        onCancel={closePauseModal}
      />
      <PlannerCompletionPathModal
        isOpen={pathModalTaskId !== null}
        filePath={filePathInputValue}
        isSaving={isSavingCompletionPath}
        onFilePathChange={setFilePathInputValue}
        onSavePath={() => void handleSaveCompletionPath()}
        onCancel={closeCompletionPathModal}
      />
      <PlannerTaskModal
        key={modalKey}
        task={modalTaskPayload}
        mode={modalMode}
        templates={templates}
        assigneeOptions={profileAssignees}
        isOpen={modalOpen}
        onClose={closeTaskModal}
        onSave={updateTask}
        onCreate={handleCreateTask}
        onSaveAsTemplate={handleSaveAsTemplate}
        onDelete={deleteTask}
        onPauseTask={requestPauseTask}
        onResumeTask={resumeTask}
      />
    </div>
  );
}
